/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(square2_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4a9d2b59b52d0c69c4b2857071b9b7c6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <howto/square2_ff.h>
// pydoc.h is automatically generated in the build directory
#include <square2_ff_pydoc.h>

void bind_square2_ff(py::module& m)
{

    using square2_ff    = ::gr::howto::square2_ff;


    py::class_<square2_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<square2_ff>>(m, "square2_ff", D(square2_ff))

        .def(py::init(&square2_ff::make),
           D(square2_ff,make)
        )
        



        ;




}








